schema: # Comma separated column names - ignored if not specified
  ordinal_cols: 
  date_columns: policy_bind_date, incident_date


data:
  input_path: data/insurance_claims.csv
  train_split_path: artifacts/data/train_data.csv
  test_split_path: artifacts/data/test_data.csv
  target_column: fraud_reported
  transformer_path: artifacts/data/data_transformer.pkl
  

model:
  model_task: classification # regression/classification
  trained_models_path: artifacts/models/a.trained_models/
  final_model_path: artifacts/models/b.final_model/model.pkl
  selected_model: # value if when you have finalized your model and want to fine tune just that; else leave blank


evaluation:
  is_binary: True # True if binary classification/Ignored for regression
  pos_label: N # One of class labels - only needed for binary classification
  eval_metrics: precision_score, recall_score, accuracy_score
  eval_metric_selection: accuracy_score # Can only provide one metric here as best model selection criteria
  eval_scores_path: artifacts/models/c.evaluation_score/scores.json
  mlflow_uri: # Uses local if not specified