schema:
  one_hot_cols:
  binary_map_cols:
  ordinal_cols:
  numerical_cols:
  date_columns: policy_bind_date, incident_date


data:
  input_path: data/insurance_claims.csv
  train_split_path: artifacts/data/train_data.csv
  test_split_path: artifacts/data/test_data.csv
  target_column: fraud_reported
  transformer_path: artifacts/data/data_transformer.pkl
  

model:
  model_task: classification # regression/classification
  trained_models_path: artifacts/models/a.trained_models/
  final_model_path: artifacts/models/b.final_model/model.pkl


evaluation:
  eval_metrics: accuracy_score
  eval_metric_selection: accuracy_score # Can only provide one metric here as best model selection criteria
  eval_scores_path: artifacts/models/c.evaluation_score/scores.json
  mlflow_uri: